server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useSSL=false&serverTimezone=UTC
    username: root
    password: root

# remote service url config
remote:
  workflow:
    url: http://localhost:9090

mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true

